= Day 1 June 25, 2024


1. Parallel concepts (2.2.)
    1) Need good justification for ACCESS for CPU and GPU to convince
    2)     2.2_parallel_computing_concepts/Parallel concepts CIML.pdf
    3) **High throughput jobs** is when running many small jobs that use one core or one gpu
    4) Threads and processes are both independent sequences of execution
    5) Being aware of threads and processes will help you understand how your code is utilizing the hardware and identify common problems.
    6) MPI is for parallelizing C, C++ and Fortran code, is the defacto standard.
    7) Horovod and NCCL for parallelizing deep learning application.
    8) MPI pretty low level between assembly and C
    9) Use appropriate MPI wrappers
    10) MPI is library, OpenMP is an interface
    11) OpenMP more readable than MPI
    12)MPICH and OpenMPI are just implementation for MPI
    13) GCC includes and implements OpenMP standard
    14) 1 process per core on MPI
    15) Hybrid apps what balance, best way is to do benchmarking and see what works best
    16) Throwing more hardware it won't make faster and amdahl`s law is important
    17) Fraction means amount of work, not lines of code in amdal`s law
    18) The amount of serial will always limit your speed
    19) Another big problem is uneven load balancing
    20) Divide large problem into small chunks
    21) How do we know how many CPUs/GPUs to use. only way to do **scaling study**  for a **representative problem** is run on a different number of processors.
    22) Right way of scaling plot is **log axes**, code in https://github.com/hovo1990/Parallel-computing-concepts 
    23) close to 100% efficiency, nextflow also creates automatic checkpoints, jobs only running for 48 hours on the SDSC Expanse
2. Batch jobs with slurm
    1) HPC compute node dell c4140 in expanse with xeon gold 6248 and tesla v100
    2) ./2.3_getting_started_with_batch_jobs_scheduling/run-tf2-train-cnn-cifar.sh
    3) Interactive vs Batch computing
    4) Batch job is a pre-scripted sets of commands
    5) batch job scheduler is air traffic controller analogy
    6) 